### PR TITLE
Fix graal-native-image profile native-image.propeties folder naming

### PR DESCRIPTION
**Pull request by lkonya**
Fixes https://github.com/micronaut-projects/micronaut-profiles/issues/121

### CODE REVIEW

**Comment by ilopmar** [comment]
@graemerocher Isn't this change going to break something? I remember you added the `-application` suffix to the folder a few weeks ago in this commit https://github.com/micronaut-projects/micronaut-profiles/commit/a27806684d3d3a6c7da2e3ca8520b398a0a18fbf to avoid the `native-image.properties` conflicts?

**Comment by graemerocher** [comment]
Ah yeah we need `-application` in both, so the fix is the wrong way round

**Comment by graemerocher** [comment]
@ilopmar could you make it so?

**Comment by ilopmar** [comment]
@graemerocher Just adding `-application` to graal and aws, right?

**Comment by lkonya** [comment]
Would this code (https://github.com/micronaut-projects/micronaut-core/blob/master/graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java#L250) work with the `-application` suffix?

**Comment by graemerocher** [comment]
that code is for the generated native image properties files, it doesn't need to the suffix

**Comment by lkonya** [comment]
Ohh, I see, my bad, sorry.

**Comment by ilopmar** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-profiles/commit/62c49c8d985029c4ad2945be93267df3dff68c01

**Pull request merged**
