### PR TITLE
Use scratch as base image

### PR DESCRIPTION
**Pull request by ahvargas**
-  Create statically linked executable so binary don't need glibc

### CODE REVIEW

**Comment by ilopmar** [comment]
Thanks for the PR. Before merging it I would like to try it locally to make sure everything works properly.

**Comment by ahvargas** [comment]
Hi @ilopmar  , did you find any issues ? Is there something I can do to help testing this ?

**Comment by ilopmar** [comment]
I did a quick test the other day. I was able to create the native image but it failed when starting it using scratch. I will try to take another deep look next week.

**Comment by ilopmar** [comment]
Thanks for your contribution!

**Pull request merged**
