### PR TITLE
create DockerfileAllInOne

### PR DESCRIPTION
**Pull request by jagedn**
another way to build a graalvm application using Docker multi-stage.

from the root of the proyect execute `docker build -t yourApp:yourTag -f DockerfileAllInOne`
and docker will build the image in 3 steps:

- using a gradle image will build the proyect
- using a graalvm image will build the native application
- using a typical dockerfile structure will build the final image

With this approach you don't need to have graal installed nor use bash commands

### CODE REVIEW

**Comment by jagedn** [comment]
see documentation at https://github.com/micronaut-projects/micronaut-core/pull/843

**Comment by graemerocher** [comment]
Some things...

1. Why is a Gradle needed used if `./gradlew` is used?
2. The maven build template proposed is using Gradle to build

**Comment by jagedn** [comment]
The "main" idea is to have a Dockerfile where you don't need to have nothing installed in your machine (gradle, maven, graal, etc) only Docker. This can be usefull for example to simplify CI pipelines because you don't need to run previous scripts to install graal etc

about maven build template you're right, it's a mistake, I'll review it

**Comment by graemerocher** [comment]
@jagedn would you mind signing the CLA?

**Comment by pvidasoftware** [comment]
Hi, just signed right now.
Sorry for the delay

**Comment by graemerocher** [comment]
Thanks for the PR, I updated it slightly to use an image that is based on alpine to reduce the image size:

https://github.com/micronaut-projects/micronaut-profiles/commit/b1d2dbd8f20aed65c09f4e6d40cfb8a95b22f33d

**Pull request merged**
