### PR TITLE
Add features for Tomcat, Jetty and Undertow

### PR DESCRIPTION
**Pull request by ilopmar**
This needs to be merged with https://github.com/micronaut-projects/micronaut-core/pull/2916

### CODE REVIEW

**Comment by graemerocher** [comment]
I think https://github.com/micronaut-projects/micronaut-profiles/blob/master/service/profile.yml needs updating too. Otherwise selecting these features will result in both Netty and a servlet container being configured which would be wrong. 

We would probably need to add `http-server` to the defaults like in https://github.com/micronaut-projects/micronaut-profiles/blob/master/base/profile.yml#L4

And possibly use `oneOf` as well..

**Comment by ilopmar** [comment]
Done!

**Comment by graemerocher** [comment]
One more thing, could you rename the features to `jetty-server`, `tomcat-server` etc. it is a possibility we support `jetty-client` in the future so I think we need to be more specific

**Comment by ilopmar** [comment]
Renamed.

**Pull request merged**
